<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="ClosedXML" Version="0.105.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RetalSystemAPI.DataAccess\RetalSystemAPI.DataAccess.csproj" />
    <ProjectReference Include="..\RetalSystemAPI.Models.DTOs\RetalSystemAPI.Models.DTOs.csproj" />
  </ItemGroup>

</Project>

